### PR TITLE
dsully merge

### PR DESCRIPTION
**Pull request by jimboca**

### CODE REVIEW

**Comment by jimboca** [comment]
Sorry, I was trying to merge your changes into my fork.

**Comment by dsully** [comment]
Jim - were you planning on creating a PR for your changes? This code base hardly needs another fork.

**Comment by jimboca** [comment]
I've been using my fork from the bkanuka fork for a long time and just wanted to get your fixes for new authorization.  This code definitely does not need more forks, but I need a stable one to use with my system and most everyone with forks develops on their master.

**Comment by dsully** [comment]
Well mine is targeted at Python 3.5+ with asyncio. So if you're good with that.

I also aim to maintain stability. I don't push to master unless I've tested locally. Unfortunately this code doesn't lend itself to unit or integration tests.

I'll likely be pulling in other methods on the HarmonyClient class, they aren't of use to me, but I can see how others might like to use them.

**Pull request closed without merging**
